apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-fake-component
  description: idk what i am doing
  tags:
    - go
    - website
spec:
  type: service
  owner: my-team
  lifecycle: production
